version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/vinoMamba/adp/internal/buildinfo.Version={{.Version}}
      - -X github.com/vinoMamba/adp/internal/buildinfo.Commit={{.ShortCommit}}
      - -X github.com/vinoMamba/adp/internal/buildinfo.Date={{.Date}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
